### ISSUE TITLE
numpy version issue

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#12]
When running python3.8, I get the following error in the CovidGridContagion tutorial:
```
db.py:127 INFO Database contains tables: [].
db.py:131 INFO Database drops tables: [].
Traceback (most recent call last):
  File "run_simulator.py", line 14, in <module>
    simulator.run()
  File "/Users/rusu1/tmp/Melodie/Melodie/simulator.py", line 247, in run
    self.pre_run()
  File "/Users/rusu1/tmp/Melodie/Melodie/simulator.py", line 101, in pre_run
    self.data_loader: DataLoader = self.df_loader_cls(
  File "/Users/rusu1/tmp/Melodie/Melodie/data_loader.py", line 109, in __init__
    self.setup()
  File "/Users/rusu1/tmp/CovidGridContagion/source/data_loader.py", line 18, in setup
    self.load_matrix(data_info.grid_stay_prob)
  File "/Users/rusu1/tmp/Melodie/Melodie/data_loader.py", line 182, in load_matrix
    array = table.to_numpy(matrix_info.dtype, copy=True)
  File "/Users/rusu1/tmp/Melodie/Melodie/data_loader.py", line 72, in dtype
    return np.float
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

Looks like numpy does not like `np.float` anymore. My python3.7 version ran this just fine because it used numpy version 1.21.6, whereas the python3.8 version used numpy 1.24.2.

Ideally, update the code to resolve these issues with the newest version of numpy. At the very least, fix the version in the requirements and setup.py file.

**Comment by hzyrc6011** [comment]
We commited a new fix to this problem, could you please test it? thanks!
