### ISSUE TITLE
Run analyzer from rock paper scissors

### ISSUE THREAD

**Issue by rusu24edward** [ABM4ALL/Melodie#15]
After `run_simulation` and `run_trainer` in the RockPaperScissorsTrainer tutorial, I ran `run_analyzer` and got the following error:
```
Traceback (most recent call last):
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: env_trainer_result_cov

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rusu1/tmp/Melodie/MelodieInfra/db/db.py", line 198, in read_dataframe
    return pd.read_sql(sql, self.connection)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/pandas/io/sql.py", line 590, in read_sql
    return pandas_sql.read_query(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/pandas/io/sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/pandas/io/sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "<string>", line 2, in execute
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3257, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: env_trainer_result_cov
[SQL: select * from env_trainer_result_cov]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: env_trainer_result_cov

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rusu1/tmp/Melodie/MelodieInfra/db/db.py", line 198, in read_dataframe
    return pd.read_sql(sql, self.connection)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/pandas/io/sql.py", line 590, in read_sql
    return pandas_sql.read_query(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/pandas/io/sql.py", line 1560, in read_query
    result = self.execute(*args)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/pandas/io/sql.py", line 1405, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "<string>", line 2, in execute
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
    return fn(*args, **kwargs)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3257, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/Users/rusu1/tmp/Melodie/v_melodie_38/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: env_trainer_result_cov
[SQL: select * from env_trainer_result_cov]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_analyzer.py", line 7, in <module>
    analyzer.plot_training_process()
  File "/Users/rusu1/tmp/RockPaperScissorsTrainer/source/analyzer.py", line 24, in plot_training_process
    df = self.db.read_dataframe("env_trainer_result_cov")
  File "/Users/rusu1/tmp/Melodie/MelodieInfra/db/db.py", line 203, in read_dataframe
    raise MelodieExceptions.Data.AttemptingReadingFromUnexistedTable(table_name)
MelodieInfra.exceptions.exceptions.MelodieException: Table 'env_trainer_result_cov' does not in database. <Error ID 1503>
```

**Comment by hzyrc6011** [comment]
@rusu24edward  Thanks for reporting this bug, the table name in analyzer.py was wrong and we modified it, please pull the main branch and retry.
